<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Student_classroom_model extends CI_Model
{

    public $table = 'student_classroom';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_merge() {
        $this->db->select('*');
        $this->db->from('student_classroom');
        $this->db->join('students', 'students.id = student_classroom.student_id');
        $this->db->join('classrooms', 'classrooms.id = student_classroom.classroom_id');
        return $this->db->get()->result();;
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('classroom_id', $q);
	$this->db->or_like('student_id', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('classroom_id', $q);
	$this->db->or_like('student_id', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Student_classroom_model.php */
/* Location: ./application/models/Student_classroom_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-03-11 13:06:09 */
/* http://harviacode.com */